# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Sciences Po Grad Econ
tagline:          'A group'
description:      'Boldly going wehere no grad students at <a href="http://econ.sciences-po.fr" target="_blank">The Sciences Po Department of Economics</a> have gone before.'
url:              http://graduate-econ-scipo.github.io
baseurl:          /

author:
  name:           'Tyler Abbot'
  url:            https://tyler-abbot.github.io

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/tyler-abbot/GradStudOrgSite

gems: [jekyll-paginate, jekyll-gist]

# For heroku issue to build site
exclude: [vendor]
